// CScript LINQ Query Test

// Sample data for testing
let users = [
    { id: 1, name: "Alice", age: 25, department: "Engineering", salary: 75000, active: true },
    { id: 2, name: "Bob", age: 30, department: "Engineering", salary: 85000, active: true },
    { id: 3, name: "Carol", age: 28, department: "Marketing", salary: 65000, active: false },
    { id: 4, name: "Dave", age: 35, department: "Engineering", salary: 95000, active: true },
    { id: 5, name: "Eve", age: 24, department: "Design", salary: 60000, active: true },
    { id: 6, name: "Frank", age: 40, department: "Marketing", salary: 80000, active: true }
];

let projects = [
    { id: 101, name: "Website Redesign", leaderId: 1, budget: 50000 },
    { id: 102, name: "Mobile App", leaderId: 2, budget: 100000 },
    { id: 103, name: "Marketing Campaign", leaderId: 6, budget: 30000 }
];

// LINQ helper functions (will be generated by transpiler later)
function from(collection) {
    return {
        where: function(predicate) {
            const filtered = collection.filter(predicate);
            return from(filtered);
        },
        select: function(selector) {
            return collection.map(selector);
        },
        join: function(other, outerKey, innerKey, resultSelector) {
            const results = [];
            for (let outer of collection) {
                for (let inner of other) {
                    if (outerKey(outer) === innerKey(inner)) {
                        results.push(resultSelector(outer, inner));
                    }
                }
            }
            return from(results);
        },
        groupBy: function(keySelector) {
            const groups = {};
            for (let item of collection) {
                const key = keySelector(item);
                if (!groups[key]) {
                    groups[key] = [];
                }
                groups[key].push(item);
            }
            return Object.keys(groups).map(key => ({
                key: key,
                items: groups[key],
                count: () => groups[key].length,
                sum: (selector) => groups[key].reduce((acc, item) => acc + selector(item), 0),
                average: (selector) => {
                    const sum = groups[key].reduce((acc, item) => acc + selector(item), 0);
                    return sum / groups[key].length;
                }
            }));
        },
        orderBy: function(keySelector) {
            const sorted = [...collection].sort((a, b) => {
                const aKey = keySelector(a);
                const bKey = keySelector(b);
                return aKey < bKey ? -1 : aKey > bKey ? 1 : 0;
            });
            return from(sorted);
        },
        toArray: function() {
            return collection;
        }
    };
}

// Test 1: Basic LINQ query - Active users in Engineering
console.log("=== Test 1: Basic Query ===");

let activeEngineers = from(users)
    .where(u => u.active)
    .where(u => u.department === "Engineering")
    .select(u => ({ name: u.name, salary: u.salary }))
    .toArray();

console.log("Active engineers:", activeEngineers);

// Test 2: Query with match expressions and pipeline
console.log("\n=== Test 2: Query with Match ===");

let categorizedUsers = from(users)
    .where(u => u.active)
    .select(u => withUpdate(u, {
        ageCategory: u.age.match({
            "20..29": "young",
            "30..39": "mid-career", 
            "40..49": "senior",
            _: "other"
        }),
        salaryLevel: u.salary.match({
            "0..60000": "entry",
            "60001..80000": "mid",
            "80001..200000": "senior",
            _: "executive"
        })
    }))
    |> (results => results.filter(u => u.ageCategory === "young"))
    |> (results => results.sort((a, b) => b.salary - a.salary));

console.log("Young professionals (sorted by salary):");
categorizedUsers.forEach(u => {
    console.log(`- ${u.name}: ${u.salaryLevel} level, $${u.salary}`);
});

// Test 3: Join users with projects
console.log("\n=== Test 3: Join Query ===");

let userProjects = from(users)
    .join(projects, 
          u => u.id, 
          p => p.leaderId,
          (user, project) => ({
              userName: user.name,
              userDepartment: user.department,
              projectName: project.name,
              budget: project.budget
          }))
    .toArray();

console.log("User-Project relationships:");
userProjects.forEach(up => {
    console.log(`- ${up.userName} (${up.userDepartment}) leads "${up.projectName}" ($${up.budget})`);
});

// Test 4: Group by department with aggregations
console.log("\n=== Test 4: Grouping and Aggregation ===");

let departmentStats = from(users)
    .where(u => u.active)
    .groupBy(u => u.department)
    |> (groups => groups.map(g => ({
        department: g.key,
        count: g.count(),
        totalSalary: g.sum(u => u.salary),
        averageSalary: Math.round(g.average(u => u.salary)),
        averageAge: Math.round(g.average(u => u.age))
    })))
    |> (stats => stats.sort((a, b) => b.totalSalary - a.totalSalary));

console.log("Department statistics:");
departmentStats.forEach(dept => {
    console.log(`- ${dept.department}: ${dept.count} people, Avg salary: $${dept.averageSalary}, Avg age: ${dept.averageAge}`);
});

// Test 5: Complex query combining all features
console.log("\n=== Test 5: Complex Query ===");

let topPerformers = from(users)
    .where(u => u.active && u.salary > 70000)
    .select(u => withUpdate(u, {
        performance: u.salary.match({
            "70000..79999": "good",
            "80000..89999": "excellent", 
            "90000..200000": "outstanding",
            _: "review"
        }),
        category: u.age.match({
            "20..29": u.department === "Engineering" ? "rising-star" : "promising",
            "30..39": u.department === "Engineering" ? "tech-lead" : "experienced",
            "40..49": "veteran",
            _: "senior"
        })
    }))
    .orderBy(u => u.salary)
    |> (results => results.reverse()) // Highest salary first
    |> (results => results.slice(0, 3)); // Top 3

console.log("Top 3 performers:");
topPerformers.forEach((user, index) => {
    console.log(`${index + 1}. ${user.name} - ${user.performance} (${user.category}), $${user.salary}`);
});

console.log("\n✅ LINQ query test completed!");